### ISSUE TITLE
設定画面の追加

### ISSUE THREAD

**Issue by Shanpan2** [sansai0707/Revolutionary-host-roles#19]
## 設定画面の追加
タイトル通りですが、TOHと同じで1つだけにするのか、SNRやTORなど陣営別に分けるかの設定ですよね(あってますよね)

**Comment by Shanpan2** [comment]
#20 で作成(プルリクがマージされたらこのイシュー閉じます)

**Comment by sansai0707** [comment]
陣営別が可能ならそっちのがいいね

**Comment by Shanpan2** [comment]
つまりTOHではない方がいいってことですか?

**Comment by sansai0707** [comment]
YES
