### ISSUE TITLE
名前にRHRがついてないと部屋を公開できないようにする

### ISSUE THREAD

**Issue by Shanpan2** [sansai0707/Revolutionary-host-roles#26]
## タイトル通り
MOD名がないとどういうMODかわからなくなる。そのためSNRやTOHと同様にすべきであると考えてます。(ほかの人次第でありますが)

**Comment by sansai0707** [comment]
そうだね。
renameコマンドを適用させれば使用者側にも問題なさっそう_イェーイ_

**Comment by Haroweeeeen** [comment]
制作しました
