### ISSUE TITLE
Some questions/いくつかの質問

### ISSUE THREAD

**Issue by XiezibanWrite** [sansai0707/Revolutionary-host-roles#27]
English:  Hello author, I recently found this module of yours on GitHub that is still in production, and I have a feeling that this is a module that only needs to be installed by the homeowner, right? (Also, I'd like to do a simplified Chinese translation for this mod if possible, is that okay?)

Japanese:  作者さんこんにちは、最近GitHubでまだ制作中のあなたのこのMODを見つけたのですが、これは本家がインストールすればいいだけのMODな気がするのですが、そうでしょうか？ (また、できればこのMODの中国語簡体字翻訳をしたいのですが、可能でしょうか？)

**Comment by sansai0707** [comment]
Hi.This mod works with host-onry deployments.　I realy thinks be grateful if you could translate it into Chinese.
（I can't use English well sorry<(_ _)>）

**Comment by Haroweeeeen** [comment]
Yes, this is a module that only needs to be installed by the homeowne.(maybe)
If We create a translation feature We will think about it.
はい、これはホストが入れるだけで動作します。
もし私達が翻訳機能を作ったら、考えてみようと思います。

**Comment by XiezibanWrite** [comment]
Hi, I got into your Disocrd server, but I can't find you, can you give me your id please? Thanks!
